### ISSUE TITLE
your illegal copy of "i2b2 dataset"

### ISSUE THREAD

**Issue by reastwood** [foreverwith/foreverwith.github.io#1]
Hello @foreverwith,
**Please remove the repository "[i2b2 dataset](https://github.com/Hankers3/i2b2-dataset)" from the organization Hankers3 immediately.** You are not authorized to share this data. 
As you cite in your [README](https://github.com/Hankers3/i2b2-dataset/blob/master/README.md), you got the data from the Chinese Software Developers Network, where it was posted **illegally** by [Francesco Yang](https://github.com/francescoyang). He had attempted to get the data from another GitHub user, who [correctly told him](https://github.com/desh2608/crnn-relation-classification/issues/7) it could not be shared that way.
Again, please remove your illegal copy of this data set from GitHub immediately.

**Comment by foreverwith** [comment]
Sorry, I have delete my  repository.
Your repository "foreverwith/i2b2-dataset" was successfully deleted.
I have no business with Hankers3, I will try to communicate with him to delete this repository

**Comment by foreverwith** [comment]
I have no write access to Hankers3 repository, so I cannot merge or delete any pull requests.
It seems that @hanker is the owner of Hankers3 organization.
https://github.com/Hankers3/Packet_Security/blob/master/start.sh
